version: '2.4'
services:
  mongodb:
    image: mongo:3.4-xenial
    volumes: 
      - mongo_data:/data/db
      - mongo_config:/data/configdb
    ports: 
      - "27017:27017"
  server:
    build: 
      context: ./server
      target: prod
    ports: 
      - "3005:3005"
    volumes: 
        - ./server:/usr/app 
    environment: 
      - DATABASE=mongodb://mongodb:27017/camonapp
      - NODE_ENV=production
    depends_on:
      - mongodb  
  client:
    build:
      context: ./client
    ports:
      - "80:80"

volumes:
  mongo_data:
  mongo_config:
  mclient_data:
